
name: Check CS61A
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 23 * * *' # Runs at 2am everyday
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install python3
      run: |
        sudo apt install python3 python3-venv

    - name: Run tests
      run: | 
        bash test.sh
      

